version: '3.8'

services:
 app:
  image: sandip7666/library:01      #link with app image 
  ports:
  - 3607:3607
  environment:
   SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/LibraryDB
   SPRING_DATASOURCE_USERNAME: admin
   SPRING_DATASOURCE_PASSWORD: Sandip7666
  depends_on:
  - db

 #initializing a new MySQL instance for Docker Compose
 db:
  image: mysql:8.0.27
  environment:
    MYSQL_ROOT_PASSWORD: Sandip7666 
    MYSQL_DATABASE: LibraryDB  
    MYSQL_USER: admin   
    MYSQL_PASSWORD: Sandip7666	